// SPDX-License-Identifier: GPL-2.0-or-later

// DESCRIPTION:
//	DSDA Config

#pragma once

#include <stdio.h>
#include "doomtype.hpp"

#ifdef __cplusplus
extern "C"
{
#endif

enum struct ConfigId : int32_t
{
	None,
	GameSpeed,
	DefaultComplevel,
	DefaultSkill,
	VanillaKeymap,
	MenuBackground,
	ProcessPriority,
	MaxPlayerCorpse,
	InputProfile,
	WeaponChoice1,
	WeaponChoice2,
	WeaponChoice3,
	WeaponChoice4,
	WeaponChoice5,
	WeaponChoice6,
	WeaponChoice7,
	WeaponChoice8,
	WeaponChoice9,
	FlashingHom,
	DemoSmoothturns,
	DemoSmoothturnsfactor,
	WeaponAttackAlignment,
	StsColoredNumbers,
	StsPctAlwaysGray,
	StsTraditionalKeys,
	StsSolidBgColor,
	StrictMode,
	Vertmouse,
	Freelook,
	Autorun,
	ShowMessages,
	CommandDisplay,
	CoordinateDisplay,
	ShowMinimap,
	ShowFps,
	ShowLevelSplits,
	Exhud,
	FreeText,
	MuteSfx,
	MuteMusic,
	MuteUnfocusedWindow,
	CheatCodes,
	OrganizeFailedDemos,
	Script0,
	Script1,
	Script2,
	Script3,
	Script4,
	Script5,
	Script6,
	Script7,
	Script8,
	Script9,
	OverrunSpechitWarn,
	OverrunSpechitEmulate,
	OverrunRejectWarn,
	OverrunRejectEmulate,
	OverrunInterceptWarn,
	OverrunInterceptEmulate,
	OverrunPlayeringameWarn,
	OverrunPlayeringameEmulate,
	OverrunDonutWarn,
	OverrunDonutEmulate,
	OverrunMissedbacksideWarn,
	OverrunMissedbacksideEmulate,
	ComperrPassuse,
	ComperrHangsolid,
	ComperrBlockmap,
	MapcolorBack,
	MapcolorGrid,
	MapcolorWall,
	MapcolorFchg,
	MapcolorCchg,
	MapcolorClsd,
	MapcolorRkey,
	MapcolorBkey,
	MapcolorYkey,
	MapcolorRdor,
	MapcolorBdor,
	MapcolorYdor,
	MapcolorTele,
	MapcolorSecr,
	MapcolorRevsecr,
	MapcolorTagfinder,
	MapcolorExit,
	MapcolorExitsecr,
	MapcolorUnsn,
	MapcolorFlat,
	MapcolorSprt,
	MapcolorItem,
	MapcolorHair,
	MapcolorSngl,
	MapcolorMe,
	MapcolorEnemy,
	MapcolorFrnd,
	MapcolorTrail1,
	MapcolorTrail2,
	MapcolorPickup,
	GlSkymode,
	GlRenderMultisampling,
	GlRenderFov,
	GlHealthBar,
	GlUsevbo,
	GlFadeMode,
	UseMouse,
	MouseSensitivityHoriz,
	MouseSensitivityVert,
	MouseAcceleration,
	MouseSensitivityMlook,
	MouseStutterCorrection,
	MouseDoubleclickAsUse,
	MouseCarrytics,
	MovementMouseinvert,
	MovementMousestrafedivisor,
	FineSensitivity,
	UseGameController,
	DehApplyCheats,
	MovementStrafe50,
	MovementStrafe50onturns,
	MovementShorttics,
	ScreenshotDir,
	StartupDelayMs,
	PitchedSounds,
	FullSounds,
	SndSamplerate,
	SndSamplecount,
	SfxVolume,
	MusicVolume,
	MusPauseOpt,
	SndChannels,
	SndMidiplayer,
	SndMididev,
	SndSoundfont,
	MusFluidsynthChorus,
	MusFluidsynthReverb,
	MusFluidsynthGain,
	MusFluidsynthChorusDepth,
	MusFluidsynthChorusLevel,
	MusFluidsynthReverbDamp,
	MusFluidsynthReverbLevel,
	MusFluidsynthReverbWidth,
	MusFluidsynthReverbRoomSize,
	MusOplGain,
	MusOplOpl3mode,
	MusPortmidiResetType,
	MusPortmidiResetDelay,
	MusPortmidiFilterSysex,
	MusPortmidiReverbLevel,
	MusPortmidiChorusLevel,
	CapSoundcommand,
	CapVideocommand,
	CapMuxcommand,
	CapTempfile1,
	CapTempfile2,
	CapRemoveTempfiles,
	CapWipescreen,
	CapFps,
	HudaddCrosshairColor,
	HudaddCrosshairTargetColor,
	HudDisplayed,
	HudaddSecretarea,
	HudaddDemoprogressbar,
	HudaddCrosshairScale,
	HudaddCrosshairHealth,
	HudaddCrosshairTarget,
	HudaddCrosshairLockTarget,
	HudaddCrosshair,
	HudHealthRed,
	HudHealthYellow,
	HudHealthGreen,
	HudAmmoRed,
	HudAmmoYellow,
	PlaybackMouseControls,
	CycleGhostColors,
	AutoKeyFrameInterval,
	AutoKeyFrameDepth,
	AutoKeyFrameTimeout,
	AutoSave,
	ExTextScaleX,
	ExTextRatioY,
	WipeAtFullSpeed,
	ShowDemoAttempts,
	HideHorns,
	HideWeapon,
	OrganizedSaves,
	CommandHistorySize,
	HideEmptyCommands,
	SkipQuitPrompt,
	ShowSplitData,
	PlayerName,
	QuickstartCacheTics,
	DeathUseAction,
	AllowJumping,
	AlwaysPistolStart,
	PistolStart,
	RespawnMonsters,
	FastMonsters,
	NoMonsters,
	CoopSpawns,
	ParallelSfxLimit,
	ParallelSfxWindow,
	MovementToggleSfx,
	SwitchWhenAmmoRunsOut,
	SwitchWeaponOnPickup,
	Viewbob,
	Weaponbob,
	FixViewbobFloorJolt,
	QuakeIntensity,
	MapBlinkingLocks,
	MapSecretAfter,
	MapCoordinates,
	MapTotals,
	MapTime,
	MapTitle,
	MapTrail,
	MapTrailCollisions,
	MapTrailSize,
	MapTraces,
	AutomapOverlay,
	AutomapRotate,
	AutomapFollow,
	AutomapGrid,
	MapGridSize,
	MapPanSpeed,
	MapScrollSpeed,
	MapWheelZoom,
	MapUseMultisamling,
	MapTextured,
	MapTexturedTrans,
	MapTexturedOverlayTrans,
	MapLinesOverlayTrans,
	MapThingsAppearance,
	Videomode,
	ScreenResolution,
	CustomResolution,
	UseFullscreen,
	ExclusiveFullscreen,
	RenderVsync,
	UncappedFramerate,
	FpsLimit,
	BackgroundFpsLimit,
	Usegamma,
	Screenblocks,
	SdlVideoWindowPos,
	SdlVideoDisplayIndex,
	PaletteOndamage,
	PaletteOnbonus,
	PaletteOnpowers,
	RenderWipescreen,
	RenderScreenMultiply,
	IntegerScaling,
	RenderAspect,
	RenderDoomLightmaps,
	FakeContrastMode,
	RenderStretchHud,
	RenderPatchesScalex,
	RenderPatchesScaley,
	RenderStretchsky,
	RenderLinearsky,
	AspectRatioCorrection,
	TranslucentSprites,
	TranslucentGhosts,
	ShowAliveMonsters,
	LeftAnalogDeadzone,
	RightAnalogDeadzone,
	LeftTriggerDeadzone,
	RightTriggerDeadzone,
	LeftAnalogSensitivityX,
	LeftAnalogSensitivityY,
	RightAnalogSensitivityX,
	RightAnalogSensitivityY,
	AnalogLookAcceleration,
	SwapAnalogs,
	InvertAnalogLook,
	ShowEndoom,
	ExportEndoom,
	AnsiEndoom,
	QuitSounds,
	AnnounceMap,
	ExtraLevelBrightness,
	DemoEndQuit,
	Count,
};

enum struct ConfigType : int32_t
{
	Int,
	String,
};

void dsda_UpdateStrictMode();
dboolean dsda_IsStrictConfig(ConfigId id);
void dsda_TrackConfigFeatures();
void dsda_RevertIntConfig(ConfigId id);
int dsda_MaxConfigLength();
void dsda_InitConfig();
dboolean dsda_ReadConfig(const char* name, const char* string_param, int int_param);
void dsda_WriteConfig(ConfigId id, int key_length, FILE* file);
void dsda_ApplyAdHocConfiguration();
int dsda_ToggleConfig(ConfigId id, dboolean persist);
int dsda_IncrementIntConfig(ConfigId id, dboolean persist);
int dsda_DecrementIntConfig(ConfigId id, dboolean persist);
int dsda_CycleConfig(ConfigId id, dboolean persist);
int dsda_UpdateIntConfig(ConfigId id, int value, dboolean persist);
const char* dsda_UpdateStringConfig(ConfigId id, const char* value, dboolean persist);
int dsda_IntConfig(ConfigId id);
int dsda_TransientIntConfig(ConfigId id);
const char* dsda_StringConfig(ConfigId id);
char* dsda_ConfigSummary(const char* name);
int dsda_ConfigIDByName(const char* name);
ConfigType dsda_ConfigType(ConfigId id);

#ifdef __cplusplus
}
#endif
