// SPDX-License-Identifier: GPL-2.0-or-later

// DESCRIPTION:
//	DSDA Game Controller

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

// Must match SDL
typedef enum
{
	DSDA_CONTROLLER_BUTTON_A,
	DSDA_CONTROLLER_BUTTON_B,
	DSDA_CONTROLLER_BUTTON_X,
	DSDA_CONTROLLER_BUTTON_Y,
	DSDA_CONTROLLER_BUTTON_BACK,
	DSDA_CONTROLLER_BUTTON_GUIDE,
	DSDA_CONTROLLER_BUTTON_START,
	DSDA_CONTROLLER_BUTTON_LEFTSTICK,
	DSDA_CONTROLLER_BUTTON_RIGHTSTICK,
	DSDA_CONTROLLER_BUTTON_LEFTSHOULDER,
	DSDA_CONTROLLER_BUTTON_RIGHTSHOULDER,
	DSDA_CONTROLLER_BUTTON_DPAD_UP,
	DSDA_CONTROLLER_BUTTON_DPAD_DOWN,
	DSDA_CONTROLLER_BUTTON_DPAD_LEFT,
	DSDA_CONTROLLER_BUTTON_DPAD_RIGHT,
	DSDA_CONTROLLER_BUTTON_MISC1,
	DSDA_CONTROLLER_BUTTON_PADDLE1,
	DSDA_CONTROLLER_BUTTON_PADDLE2,
	DSDA_CONTROLLER_BUTTON_PADDLE3,
	DSDA_CONTROLLER_BUTTON_PADDLE4,
	DSDA_CONTROLLER_BUTTON_TOUCHPAD,
	DSDA_CONTROLLER_BUTTON_TRIGGERLEFT,
	DSDA_CONTROLLER_BUTTON_TRIGGERRIGHT,
	DSDA_CONTROLLER_BUTTON_MAX,
} dsda_game_controller_button_t;

const char* dsda_GameControllerButtonName(int button);
void dsda_PollGameController();
void dsda_PollGameControllerButtons();
void dsda_InitGameController();

#ifdef __cplusplus
}
#endif
