// SPDX-License-Identifier: GPL-2.0-or-later

// DESCRIPTION:
// DSDA Line Special

#pragma once

#ifdef __cplusplus
extern "C"
{
#endif

enum struct ZDoomStaticInit : int32_t
{
	Gravity     = 0,
	Color       = 1,
	Damage      = 2,
	SectorLink = 3,

	EdSector    = 253,
	EdLine      = 254,
	TransferSky = 255
};

enum struct ZDoomLineSpecial : int32_t
{
	PolyobjStartLine                  = 1,
	PolyobjRotateLeft                 = 2,
	PolyobjRotateRight                = 3,
	PolyobjMove                        = 4,
	PolyobjExplicitLine               = 5,
	PolyobjMoveTimes8                = 6,
	PolyobjDoorSwing                  = 7,
	PolyobjDoorSlide                  = 8,
	LineHorizon                        = 9,
	DoorClose                          = 10,
	DoorOpen                           = 11,
	DoorRaise                          = 12,
	DoorLockedRaise                   = 13,
	//zl_door_animated                       = 14,
	//zl_autosave                            = 15,
	//zl_transfer_wall_light                 = 16,
	ThingRaise                         = 17,
	//zl_start_conversation                  = 18,
	ThingStop                          = 19,
	FloorLowerByValue                = 20,
	FloorLowerToLowest               = 21,
	FloorLowerToNearest              = 22,
	FloorRaiseByValue                = 23,
	FloorRaiseToHighest              = 24,
	FloorRaiseToNearest              = 25,
	StairsBuildDown                   = 26,
	StairsBuildUp                     = 27,
	FloorRaiseAndCrush               = 28,
	PillarBuild                        = 29,
	PillarOpen                         = 30,
	StairsBuildDownSync              = 31,
	StairsBuildUpSync                = 32,
	ForceField                         = 33,
	ClearForceField                   = 34,
	FloorRaiseByValueTimes8        = 35,
	FloorLowerByValueTimes8        = 36,
	FloorMoveToValue                 = 37,
	CeilingWaggle                      = 38,
	TeleportZombieChanger             = 39,
	CeilingLowerByValue              = 40,
	CeilingRaiseByValue              = 41,
	CeilingCrushAndRaise             = 42,
	CeilingLowerAndCrush             = 43,
	CeilingCrushStop                  = 44,
	CeilingCrushRaiseAndStay        = 45,
	FloorCrushStop                    = 46,
	CeilingMoveToValue               = 47,
	//zl_sector_attach_3d_midtex             = 48,
	//zl_glass_break                         = 49,
	//zl_extra_floor_light_only              = 50,
	//zl_sector_set_link                     = 51,
	ScrollWall                         = 52,
	LineSetTextureOffset             = 53,
	SectorChangeFlags                 = 54,
	LineSetBlocking                   = 55,
	LineSetTexturescale               = 56,
	//zl_sector_set_portal                   = 57,
	SectorCopyScroller                = 58,
	PolyobjOrMoveToSpot             = 59,
	PlatPerpetualRaise                = 60,
	PlatStop                           = 61,
	PlatDownWaitUpStay              = 62,
	PlatDownByValue                  = 63,
	PlatUpWaitDownStay              = 64,
	PlatUpByValue                    = 65,
	FloorLowerInstant                 = 66,
	FloorRaiseInstant                 = 67,
	FloorMoveToValueTimes8         = 68,
	CeilingMoveToValueTimes8       = 69,
	Teleport                            = 70,
	TeleportNoFog                     = 71,
	ThrustThing                        = 72,
	DamageThing                        = 73,
	TeleportNewMap                    = 74,
	TeleportEndGame                   = 75,
	TeleportOther                      = 76,
	TeleportGroup                      = 77,
	TeleportInSector                  = 78,
	//zl_thing_set_conversation              = 79,
	//zl_acs_execute                         = 80,
	//zl_acs_suspend                         = 81,
	//zl_acs_terminate                       = 82,
	//zl_acs_locked_execute                  = 83,
	//zl_acs_execute_with_result             = 84,
	//zl_acs_locked_execute_door             = 85,
	PolyobjMoveToSpot                = 86,
	PolyobjStop                        = 87,
	PolyobjMoveTo                     = 88,
	PolyobjOrMoveTo                  = 89,
	PolyobjOrRotateLeft              = 90,
	PolyobjOrRotateRight             = 91,
	PolyobjOrMove                     = 92,
	PolyobjOrMoveTimes8             = 93,
	PillarBuildAndCrush              = 94,
	FloorAndCeilingLowerByValue    = 95,
	FloorAndCeilingRaiseByValue    = 96,
	CeilingLowerAndCrushDist        = 97,
	//zl_sector_set_translucent              = 98,
	FloorRaiseAndCrushdoom           = 99,
	ScrollTextureLeft                 = 100,
	ScrollTextureRight                = 101,
	ScrollTextureUp                   = 102,
	ScrollTextureDown                 = 103,
	CeilingCrushAndRaiseSilentDist = 104,
	DoorWaitRaise                     = 105,
	DoorWaitClose                     = 106,
	//zl_line_set_portal_target              = 107,

	//zl_light_force_lightning   = 109,
	LightRaiseByValue    = 110,
	LightLowerByValue    = 111,
	LightChangeToValue   = 112,
	LightFade              = 113,
	LightGlow              = 114,
	LightFlicker           = 115,
	LightStrobe            = 116,
	LightStop              = 117,
	//zl_plane_copy              = 118,
	ThingDamage            = 119,
	RadiusQuake            = 120,
	LineSetIdentification = 121,

	ThingMove = 125,

	ThingSetSpecial        = 127,
	ThrustThingZ           = 128,
	//zl_use_puzzle_item          = 129,
	ThingActivate           = 130,
	ThingDeactivate         = 131,
	ThingRemove             = 132,
	ThingDestroy            = 133,
	ThingProjectile         = 134,
	ThingSpawn              = 135,
	ThingProjectileGravity = 136,
	ThingSpawnNoFog       = 137,
	FloorWaggle             = 138,
	ThingSpawnFacing       = 139,
	//zl_sector_change_sound      = 140,

	TeleportNoStop = 154,

	//zl_line_set_portal             = 156,
	//zl_set_global_fog_parameter    = 157,
	//zl_fs_execute                  = 158,
	//zl_sector_set_plane_reflection = 159,
	//zl_sector_set_3d_floor         = 160,
	//zl_sector_set_contents         = 161,

	CeilingCrushAndRaiseDist       = 168,
	GenericCrusher2                   = 169,
	SectorSetCeilingScale2          = 170,
	SectorSetFloorScale2            = 171,
	PlatUpNearestWaitDownStay     = 172,
	NoiseAlert                        = 173,
	//zl_send_to_communicator               = 174,
	ThingProjectileIntercept         = 175,
	ThingChangeTid                   = 176,
	ThingHate                         = 177,
	ThingProjectileAimed             = 178,
	//zl_change_skill                       = 179,
	//zl_thing_set_translation              = 180,
	//zl_plane_align                        = 181,
	//zl_line_mirror                        = 182,
	//zl_line_align_ceiling                 = 183,
	//zl_line_align_floor                   = 184,
	SectorSetRotation                = 185,
	SectorSetCeilingPanning         = 186,
	SectorSetFloorPanning           = 187,
	SectorSetCeilingScale           = 188,
	SectorSetFloorScale             = 189,
	StaticInit                        = 190,
	//zl_set_player_property                = 191,
	CeilingLowerToHighestFloor     = 192,
	CeilingLowerInstant              = 193,
	CeilingRaiseInstant              = 194,
	CeilingCrushRaiseAndStayA     = 195,
	CeilingCrushAndRaiseA          = 196,
	CeilingCrushAndRaiseSilentA   = 197,
	CeilingRaiseByValueTimes8     = 198,
	CeilingLowerByValueTimes8     = 199,
	GenericFloor                      = 200,
	GenericCeiling                    = 201,
	GenericDoor                       = 202,
	GenericLift                       = 203,
	GenericStairs                     = 204,
	GenericCrusher                    = 205,
	PlatDownWaitUpStayLip         = 206,
	PlatPerpetualRaiseLip           = 207,
	TranslucentLine                   = 208,
	TransferHeights                   = 209,
	TransferFloorLight               = 210,
	TransferCeilingLight             = 211,
	//zl_sector_set_color                   = 212,
	//zl_sector_set_fade                    = 213,
	SectorSetDamage                  = 214,
	TeleportLine                      = 215,
	SectorSetGravity                 = 216,
	StairsBuildUpDoom               = 217,
	SectorSetWind                    = 218,
	SectorSetFriction                = 219,
	SectorSetCurrent                 = 220,
	ScrollTextureBoth                = 221,
	ScrollTextureModel               = 222,
	ScrollFloor                       = 223,
	ScrollCeiling                     = 224,
	ScrollTextureOffsets             = 225,
	//zl_acs_execute_always                 = 226,
	PointPushSetForce               = 227,
	PlatRaiseAndStayTx0            = 228,
	//zl_thing_set_goal                     = 229,
	PlatUpByValueStayTx           = 230,
	PlatToggleCeiling                = 231,
	LightStrobeDoom                  = 232,
	LightMinNeighbor                 = 233,
	LightMaxNeighbor                 = 234,
	FloorTransferTrigger             = 235,
	FloorTransferNumeric             = 236,
	//zl_change_camera                      = 237,
	FloorRaiseToLowestCeiling      = 238,
	FloorRaiseByValueTxTy         = 239,
	FloorRaiseByTexture             = 240,
	FloorLowerToLowestTxTy        = 241,
	FloorLowerToHighest             = 242,
	ExitNormal                        = 243,
	ExitSecret                        = 244,
	ElevatorRaiseToNearest          = 245,
	ElevatorMoveToFloor             = 246,
	ElevatorLowerToNearest          = 247,
	HealThing                         = 248,
	DoorCloseWaitOpen               = 249,
	FloorDonut                        = 250,
	FloorAndCeilingLowerRaise      = 251,
	CeilingRaiseToNearest           = 252,
	CeilingLowerToLowest            = 253,
	CeilingLowerToFloor             = 254,
	CeilingCrushRaiseAndStaySilA = 255,

	FloorLowerToHighestEe      = 256,
	FloorRaiseToLowest          = 257,
	FloorLowerToLowestCeiling  = 258,
	FloorRaiseToCeiling         = 259,
	FloorToCeilingInstant       = 260,
	FloorLowerByTexture         = 261,
	CeilingRaiseToHighest       = 262,
	CeilingToHighestInstant     = 263,
	CeilingLowerToNearest       = 264,
	CeilingRaiseToLowest        = 265,
	CeilingRaiseToHighestFloor = 266,
	CeilingToFloorInstant       = 267,
	CeilingRaiseByTexture       = 268,
	CeilingLowerByTexture       = 269,
	StairsBuildDownDoom         = 270,
	StairsBuildUpDoomSync      = 271,
	StairsBuildDownDoomSync    = 272,

	StairsBuildUpDoomCrush      = 273,
	//zl_door_animated_close = 274,
	FloorStop                      = 275,
	CeilingStop                    = 276,
	//zl_sector_set_floor_glow = 277,
	//zl_sector_set_ceiling_glow = 278,
	FloorMoveToValueAndCrush   = 279,
	CeilingMoveToValueAndCrush = 280,
	LineSetAutomapFlags          = 281,
	LineSetAutomapStyle          = 282,
	//zl_polyobj_stop_sound = 283,
	//zl_generic_crusher_dist = 284,

	MapSetColormap    = 2701,
	SectorSetColormap = 2702,
	MusicChangeSong   = 2703,
	MusicStop          = 2704,

	LinespecialMax
};

#ifdef __cplusplus
}
#endif
