# PrBoom main executable

set(COMMON_SRC
    am_map.cpp
    am_map.hpp
    doomdata.hpp
    doomdef.cpp
    doomdef.hpp
    doomstat.cpp
    doomstat.hpp
    doomtype.hpp
    dsda.cpp
    dsda.hpp
    dsda/aim.cpp
    dsda/aim.hpp
    dsda/ambient.cpp
    dsda/ambient.hpp
    dsda/analysis.cpp
    dsda/analysis.hpp
    dsda/analysis_category.hpp
    dsda/analysis_report.hpp
    dsda/args.cpp
    dsda/args.hpp
    dsda/brute_force.cpp
    dsda/brute_force.hpp
    dsda/build.cpp
    dsda/build.hpp
    dsda/compatibility.cpp
    dsda/compatibility.hpp
    dsda/configuration.cpp
    dsda/configuration.hpp
    dsda/console.cpp
    dsda/console.hpp
    dsda/cr_table.cpp
    dsda/cr_table.hpp
    dsda/data_organizer.cpp
    dsda/data_organizer.hpp
    dsda/death.cpp
    dsda/death.hpp
    dsda/deh_hash.cpp
    dsda/deh_hash.hpp
    dsda/demo.cpp
    dsda/demo.hpp
    dsda/destructible.cpp
    dsda/destructible.hpp
    dsda/endoom.cpp
    dsda/endoom.hpp
    dsda/episode.cpp
    dsda/episode.hpp
    dsda/excmd.cpp
    dsda/excmd.hpp
    dsda/exdemo.cpp
    dsda/exdemo.hpp
    dsda/exdemo_signature.hpp
    dsda/exhud.cpp
    dsda/exhud.hpp
    dsda/features.cpp
    dsda/features.hpp
    dsda/font.cpp
    dsda/font.hpp
    dsda/game_controller.cpp
    dsda/game_controller.hpp
    dsda/gameinfo.cpp
    dsda/gameinfo.hpp
    dsda/ghost.cpp
    dsda/ghost.hpp
    dsda/gl/render_scale.cpp
    dsda/gl/render_scale.hpp
    dsda/global.cpp
    dsda/global.hpp
    dsda/hud_components.hpp
    dsda/hud_components/ammo_text.cpp
    dsda/hud_components/ammo_text.hpp
    dsda/hud_components/armor_text.cpp
    dsda/hud_components/armor_text.hpp
    dsda/hud_components/attempts.cpp
    dsda/hud_components/attempts.hpp
    dsda/hud_components/base.cpp
    dsda/hud_components/base.hpp
    dsda/hud_components/big_ammo.cpp
    dsda/hud_components/big_ammo.hpp
    dsda/hud_components/big_armor.cpp
    dsda/hud_components/big_armor.hpp
    dsda/hud_components/big_armor_text.cpp
    dsda/hud_components/big_armor_text.hpp
    dsda/hud_components/big_artifact.cpp
    dsda/hud_components/big_artifact.hpp
    dsda/hud_components/big_health.cpp
    dsda/hud_components/big_health.hpp
    dsda/hud_components/big_health_text.cpp
    dsda/hud_components/big_health_text.hpp
    dsda/hud_components/color_test.cpp
    dsda/hud_components/color_test.hpp
    dsda/hud_components/command_display.cpp
    dsda/hud_components/command_display.hpp
    dsda/hud_components/composite_time.cpp
    dsda/hud_components/composite_time.hpp
    dsda/hud_components/coordinate_display.cpp
    dsda/hud_components/coordinate_display.hpp
    dsda/hud_components/event_split.cpp
    dsda/hud_components/event_split.hpp
    dsda/hud_components/fps.cpp
    dsda/hud_components/fps.hpp
    dsda/hud_components/free_text.cpp
    dsda/hud_components/free_text.hpp
    dsda/hud_components/health_text.cpp
    dsda/hud_components/health_text.hpp
    dsda/hud_components/keys.cpp
    dsda/hud_components/keys.hpp
    dsda/hud_components/level_splits.cpp
    dsda/hud_components/level_splits.hpp
    dsda/hud_components/line_display.cpp
    dsda/hud_components/line_display.hpp
    dsda/hud_components/line_distance_tracker.cpp
    dsda/hud_components/line_distance_tracker.hpp
    dsda/hud_components/line_tracker.cpp
    dsda/hud_components/line_tracker.hpp
    dsda/hud_components/local_time.cpp
    dsda/hud_components/local_time.hpp
    dsda/hud_components/map_coordinates.cpp
    dsda/hud_components/map_coordinates.hpp
    dsda/hud_components/map_time.cpp
    dsda/hud_components/map_time.hpp
    dsda/hud_components/map_title.cpp
    dsda/hud_components/map_title.hpp
    dsda/hud_components/map_totals.cpp
    dsda/hud_components/map_totals.hpp
    dsda/hud_components/message.cpp
    dsda/hud_components/message.hpp
    dsda/hud_components/minimap.cpp
    dsda/hud_components/minimap.hpp
    dsda/hud_components/mobj_tracker.cpp
    dsda/hud_components/mobj_tracker.hpp
    dsda/hud_components/null.cpp
    dsda/hud_components/null.hpp
    dsda/hud_components/player_tracker.cpp
    dsda/hud_components/player_tracker.hpp
    dsda/hud_components/ready_ammo_text.cpp
    dsda/hud_components/ready_ammo_text.hpp
    dsda/hud_components/render_stats.cpp
    dsda/hud_components/render_stats.hpp
    dsda/hud_components/secret_message.cpp
    dsda/hud_components/secret_message.hpp
    dsda/hud_components/sector_tracker.cpp
    dsda/hud_components/sector_tracker.hpp
    dsda/hud_components/speed_text.cpp
    dsda/hud_components/speed_text.hpp
    dsda/hud_components/stat_totals.cpp
    dsda/hud_components/stat_totals.hpp
    dsda/hud_components/tracker.cpp
    dsda/hud_components/tracker.hpp
    dsda/hud_components/weapon_text.cpp
    dsda/hud_components/weapon_text.hpp
    dsda/id_list.cpp
    dsda/id_list.hpp
    dsda/input.cpp
    dsda/input.hpp
    dsda/key_frame.cpp
    dsda/key_frame.hpp
    dsda/line_special.hpp
    dsda/map_format.cpp
    dsda/map_format.hpp
    dsda/mapinfo.cpp
    dsda/mapinfo.hpp
    dsda/mapinfo/hexen.cpp
    dsda/mapinfo/hexen.hpp
    dsda/mapinfo/legacy.cpp
    dsda/mapinfo/legacy.hpp
    dsda/mapinfo/u.cpp
    dsda/mapinfo/u.hpp
    dsda/memory.cpp
    dsda/memory.hpp
    dsda/messenger.cpp
    dsda/messenger.hpp
    dsda/mobjinfo.cpp
    dsda/mobjinfo.hpp
    dsda/mouse.cpp
    dsda/mouse.hpp
    dsda/msecnode.cpp
    dsda/msecnode.hpp
    dsda/music.cpp
    dsda/music.hpp
    dsda/name.cpp
    dsda/name.hpp
    dsda/options.cpp
    dsda/options.hpp
    dsda/palette.cpp
    dsda/palette.hpp
    dsda/pause.cpp
    dsda/pause.hpp
    dsda/pclass.cpp
    dsda/pclass.hpp
    dsda/playback.cpp
    dsda/playback.hpp
    dsda/preferences.cpp
    dsda/preferences.hpp
    dsda/quake.cpp
    dsda/render_stats.cpp
    dsda/render_stats.hpp
    dsda/save.cpp
    dsda/save.hpp
    dsda/scroll.cpp
    dsda/scroll.hpp
    dsda/settings.cpp
    dsda/settings.hpp
    dsda/sfx.cpp
    dsda/sfx.hpp
    dsda/signal_context.hpp
    dsda/skill_info.cpp
    dsda/skill_info.hpp
    dsda/skip.cpp
    dsda/skip.hpp
    dsda/sndinfo.cpp
    dsda/sndinfo.hpp
    dsda/spawn_number.cpp
    dsda/spawn_number.hpp
    dsda/split_tracker.cpp
    dsda/split_tracker.hpp
    dsda/sprite.cpp
    dsda/sprite.hpp
    dsda/state.cpp
    dsda/state.hpp
    dsda/stretch.cpp
    dsda/stretch.hpp
    dsda/text_color.cpp
    dsda/text_color.hpp
    dsda/text_file.cpp
    dsda/text_file.hpp
    dsda/thing_id.cpp
    dsda/thing_id.hpp
    dsda/time.cpp
    dsda/time.hpp
    dsda/tracker.cpp
    dsda/tracker.hpp
    dsda/tranmap.cpp
    dsda/tranmap.hpp
    dsda/udmf.cpp
    dsda/udmf.hpp
    dsda/utility.cpp
    dsda/utility.hpp
    dsda/utility/string_view.cpp
    dsda/utility/string_view.hpp
    dsda/wad_stats.cpp
    dsda/wad_stats.hpp
    dsda/zipfile.cpp
    dsda/zipfile.hpp
    textscreen/doomkeys.hpp
    textscreen/txt_main.hpp
    textscreen/txt_sdl.cpp
    textscreen/txt_sdl.hpp
    textscreen/txt_utf8.cpp
    textscreen/txt_utf8.hpp
    textscreen/fonts/convert-font
    textscreen/fonts/normal.hpp
    textscreen/fonts/hauge-8x18-v1-6.png
    textscreen/fonts/README
    dstrings.cpp
    dstrings.hpp
    d_deh.cpp
    d_deh.hpp
    d_englsh.hpp
    d_event.hpp
    d_items.cpp
    d_items.hpp
    d_main.cpp
    d_main.hpp
    d_net.hpp
    d_player.hpp
    d_think.hpp
    d_ticcmd.hpp
    e6y.cpp
    e6y.hpp
    f_finale.cpp
    f_finale.hpp
    f_wipe.cpp
    f_wipe.hpp
    g_game.cpp
    g_game.hpp
    g_overflow.cpp
    g_overflow.hpp
    heretic/d_main.cpp
    heretic/def.hpp
    heretic/dstrings.hpp
    heretic/f_finale.hpp
    heretic/f_finale.cpp
    heretic/info.cpp
    heretic/in_lude.cpp
    heretic/in_lude.hpp
    heretic/level_names.cpp
    heretic/mn_menu.cpp
    heretic/mn_menu.hpp
    heretic/p_action.hpp
    heretic/sb_bar.cpp
    heretic/sb_bar.hpp
    heretic/sounds.cpp
    hexen/a_action.cpp
    hexen/a_action.hpp
    hexen/info.cpp
    hexen/f_finale.cpp
    hexen/f_finale.hpp
    hexen/h2_main.cpp
    hexen/in_lude.cpp
    hexen/in_lude.hpp
    hexen/p_acs.cpp
    hexen/p_acs.hpp
    hexen/p_anim.cpp
    hexen/p_anim.hpp
    hexen/p_things.cpp
    hexen/p_things.hpp
    hexen/po_man.cpp
    hexen/po_man.hpp
    hexen/sn_sonix.cpp
    hexen/sn_sonix.hpp
    hexen/sounds.cpp
    hexen/sv_save.cpp
    hexen/sv_save.hpp
    hu_lib.cpp
    hu_lib.hpp
    hu_stuff.cpp
    hu_stuff.hpp
    info.cpp
    info.hpp
    i_capture.cpp
    i_capture.hpp
    i_glob.cpp
    i_glob.hpp
    i_main.hpp
    i_sound.hpp
    i_system.hpp
    i_video.hpp
    lprintf.cpp
    lprintf.hpp
    md5.cpp
    md5.hpp
    m_argv.cpp
    m_argv.hpp
    m_bbox.cpp
    m_bbox.hpp
    m_cheat.cpp
    m_cheat.hpp
    m_file.cpp
    m_file.hpp
    m_fixed.hpp
    m_menu.cpp
    m_menu.hpp
    m_misc.cpp
    m_misc.hpp
    m_random.cpp
    m_random.hpp
    m_swap.hpp
    p_ceilng.cpp
    p_doors.cpp
    p_enemy.cpp
    p_enemy.hpp
    p_floor.cpp
    p_genlin.cpp
    p_inter.cpp
    p_inter.hpp
    p_lights.cpp
    p_map.cpp
    p_map.hpp
    p_maputl.cpp
    p_maputl.hpp
    p_mobj.cpp
    p_mobj.hpp
    p_plats.cpp
    p_pspr.cpp
    p_pspr.hpp
    p_saveg.cpp
    p_saveg.hpp
    p_setup.cpp
    p_setup.hpp
    p_sight.cpp
    p_spec.cpp
    p_spec.hpp
    p_switch.cpp
    p_telept.cpp
    p_tick.cpp
    p_tick.hpp
    p_user.cpp
    p_user.hpp
    r_bsp.cpp
    r_bsp.hpp
    r_data.cpp
    r_data.hpp
    r_defs.hpp
    r_draw.cpp
    r_draw.hpp
    r_fps.cpp
    r_fps.hpp
    r_main.cpp
    r_main.hpp
    r_patch.cpp
    r_patch.hpp
    r_plane.cpp
    r_plane.hpp
    r_segs.cpp
    r_segs.hpp
    r_sky.cpp
    r_sky.hpp
    r_state.hpp
    r_things.cpp
    r_things.hpp
    scanner.cpp
    scanner.hpp
    sc_man.cpp
    sc_man.hpp
    smooth.cpp
    smooth.hpp
    sounds.cpp
    sounds.hpp
    st_lib.cpp
    st_lib.hpp
    st_stuff.cpp
    st_stuff.hpp
    s_advsound.cpp
    s_advsound.hpp
    s_sound.cpp
    s_sound.hpp
    tables.cpp
    tables.hpp
    umapinfo.cpp
    umapinfo.hpp
    v_video.cpp
    v_video.hpp
    wadtbl.cpp
    wadtbl.hpp
    wi_stuff.cpp
    wi_stuff.hpp
    w_wad.cpp
    w_wad.hpp
    z_bmalloc.cpp
    z_bmalloc.hpp
    z_zone.cpp
    z_zone.hpp
)

set(NET_CLIENT_SRC
    d_client.cpp
)

if(HAVE_MMAP OR HAVE_CREATE_FILE_MAPPING)
    set(WAD_SRC w_mmap.cpp)
else()
    set(WAD_SRC w_memcache.cpp)
endif()

set(MUS2MID_SRC
    memio.cpp
    memio.hpp
    mus2mid.cpp
    mus2mid.hpp
)

set(SDLDOOM_SOURCES
    SDL/i_main.cpp
    SDL/i_sound.cpp
    SDL/i_sndfile.cpp
    SDL/i_sndfile.hpp
    SDL/i_sshot.cpp
    SDL/i_system.cpp
    SDL/i_video.cpp
)

set(DOOMMUSIC_SOURCES
    MUSIC/xmpplayer.cpp
    MUSIC/xmpplayer.hpp
    MUSIC/flplayer.cpp
    MUSIC/flplayer.hpp
    MUSIC/madplayer.cpp
    MUSIC/madplayer.hpp
    MUSIC/midifile.cpp
    MUSIC/midifile.hpp
    MUSIC/musicplayer.hpp
    MUSIC/opl.cpp
    MUSIC/opl.hpp
    MUSIC/opl3.cpp
    MUSIC/opl3.hpp
    MUSIC/oplplayer.cpp
    MUSIC/oplplayer.hpp
    MUSIC/opl_queue.cpp
    MUSIC/opl_queue.hpp
    MUSIC/wf_rom.hpp
    MUSIC/portmidiplayer.cpp
    MUSIC/portmidiplayer.hpp
    MUSIC/vorbisplayer.cpp
    MUSIC/vorbisplayer.hpp
)

set(EXTRA_FILES
    r_drawcolpipeline.inl
    r_drawcolumn.inl
    r_drawflush.inl
)

set(DSDA_SOURCES
    ${COMMON_SRC}
    ${NET_CLIENT_SRC}
    ${WAD_SRC}
    ${MUS2MID_SRC}
    ${SDLDOOM_SOURCES}
    ${DOOMMUSIC_SOURCES}
    ${EXTRA_FILES}
)

function(AddGameExecutable TARGET SOURCES)
    set(SOURCES
        ${SOURCES}
        gl_clipper.cpp
        gl_drawinfo.cpp
        gl_fbo.cpp
        gl_intern.hpp
        gl_light.cpp
        gl_main.cpp
        gl_map.cpp
        gl_missingtexture.cpp
        gl_opengl.cpp
        gl_opengl.hpp
        gl_preprocess.cpp
        gl_progress.cpp
        gl_shader.cpp
        gl_sky.cpp
        gl_struct.hpp
        gl_texture.cpp
        gl_vertex.cpp
        gl_wipe.cpp
    )

    if(WIN32)
        set(SOURCES
            ${SOURCES}
            ../ICONS/icons.rc
        )
        if(MSVC)
            set(SOURCES
                ${SOURCES}
                win_opendir.cpp
                win_opendir.hpp
            )
        endif()
    endif()

    add_executable(${TARGET} WIN32 ${SOURCES})

    dsda_target_set_warnings(${TARGET})
    dsda_target_silence_deprecation(${TARGET})
    dsda_target_enable_fast_math(${TARGET})
    dsda_target_use_config_h(${TARGET})

    target_compile_features(${TARGET}
        PRIVATE
        cxx_std_26
    )

    target_include_directories(${TARGET}
        PRIVATE
        ${CMAKE_CURRENT_SOURCE_DIR}
    )

    target_link_libraries(${TARGET}
        PRIVATE
        dsda::dependencies
    )

    set_target_properties(${TARGET} PROPERTIES
        RUNTIME_OUTPUT_DIRECTORY ${DSDA_OUTPUT_PATH}
        CXX_STANDARD 26
        CXX_STANDARD_REQUIRED ON
        CXX_EXTENSIONS OFF
    )

    add_dependencies(${TARGET} dsda-doom-wad)
    add_custom_command(TARGET ${TARGET}
        POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E echo "Copying ${WAD_DATA_PATH} to $<TARGET_FILE_DIR:dsda-doom>"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different ${WAD_DATA_PATH} $<TARGET_FILE_DIR:dsda-doom>
    )

    if(MSVC)
        set_target_properties(${TARGET} PROPERTIES
            LINK_FLAGS "/MANIFEST:NO /SUBSYSTEM:CONSOLE"
        )
        add_custom_command(TARGET ${TARGET} POST_BUILD
            COMMAND "mt.exe" -manifest \"${CMAKE_CURRENT_SOURCE_DIR}\\..\\ICONS\\dsda-doom.exe.manifest\" -outputresource:\"$<TARGET_FILE:dsda-doom>\"\;\#1
        )
    elseif(WIN32)
        set_target_properties(${TARGET} PROPERTIES
            LINK_FLAGS "-mconsole"
        )
    endif()

    if(CMAKE_VERSION VERSION_GREATER 3.20
        AND WIN32
        AND NOT VCPKG_TOOLCHAIN
        AND NOT CMAKE_CROSSCOMPILING)
        install(
            TARGETS ${TARGET}
            RUNTIME_DEPENDENCIES
                PRE_EXCLUDE_REGEXES "api-ms-" "ext-ms-"
                POST_EXCLUDE_REGEXES ".*system32/.*\\.dll"
                DIRECTORIES $<TARGET_FILE_DIR:${TARGET}> $ENV{PATH}
            RUNTIME DESTINATION "${DSDA_INSTALL_BINDIR}"
        )
    else()
        install(TARGETS ${TARGET} RUNTIME DESTINATION "${DSDA_INSTALL_BINDIR}")
    endif()
endfunction()

AddGameExecutable(dsda-doom "${DSDA_SOURCES}")
