// SPDX-License-Identifier: GPL-2.0-or-later

/* DESCRIPTION:
 *  Sprite animation.
 */

#pragma once

#include "p_mobj.hpp"
#include "m_fixed.hpp"
#include "tables.hpp"
#include "info.hpp"

#ifdef __cplusplus
extern "C"
{
#endif

/* Basic data types.
 * Needs fixed point, and BAM angles. */

/* Needs to include the precompiled sprite animation tables.
 *
 * Header generated by multigen utility.
 * This includes all the data for thing animation,
 * i.e. the Thing Atrributes table and the Frame Sequence table.
 */

/*
 * Frame flags:
 * handles maximum brightness (torches, muzzle flare, light sources)
 */

#define FF_FULLBRIGHT   0x8000  /* flag in thing->frame */
#define FF_FRAMEMASK    0x7fff

/*
 * Overlay psprites are scaled shapes
 * drawn directly on the view screen,
 * coordinates are given for a 320*200 view screen.
 */

enum struct PspNum : int32_t
{
	Weapon,
	Flash,
	Count
};

typedef struct
{
	state_t* state; /* a NULL state means not active */
	int tics;
	fixed_t sx;
	fixed_t sy;
} pspdef_t;

enum struct CenterWeapon : int32_t
{
	Off,
	Hor,
	HorVer,
	Bob,
	Count,
};

int P_WeaponPreferred(WeaponType w1, WeaponType w2);

struct player_s;
WeaponType P_SwitchWeapon(struct player_s* player);
dboolean P_CheckAmmo(struct player_s* player);
void P_SubtractAmmo(struct player_s* player, int compat_amt);
void P_SetupPsprites(struct player_s* curplayer);
void P_MovePsprites(struct player_s* curplayer);
void P_DropWeapon(struct player_s* player);
int P_AmmoPercent(struct player_s* player, WeaponType weapon);

void A_Light0(struct player_s* player, pspdef_t* psp);
void A_WeaponReady(struct player_s* player, pspdef_t* psp);
void A_Lower(struct player_s* player, pspdef_t* psp);
void A_Raise(struct player_s* player, pspdef_t* psp);
void A_Punch(struct player_s* player, pspdef_t* psp);
void A_ReFire(struct player_s* player, pspdef_t* psp);
void A_FirePistol(struct player_s* player, pspdef_t* psp);
void A_Light1(struct player_s* player, pspdef_t* psp);
void A_FireShotgun(struct player_s* player, pspdef_t* psp);
void A_Light2(struct player_s* player, pspdef_t* psp);
void A_FireShotgun2(struct player_s* player, pspdef_t* psp);
void A_CheckReload(struct player_s* player, pspdef_t* psp);
void A_OpenShotgun2(struct player_s* player, pspdef_t* psp);
void A_LoadShotgun2(struct player_s* player, pspdef_t* psp);
void A_CloseShotgun2(struct player_s* player, pspdef_t* psp);
void A_FireCGun(struct player_s* player, pspdef_t* psp);
void A_GunFlash(struct player_s* player, pspdef_t* psp);
void A_FireMissile(struct player_s* player, pspdef_t* psp);
void A_Saw(struct player_s* player, pspdef_t* psp);
void A_FirePlasma(struct player_s* player, pspdef_t* psp);
void A_BFGsound(struct player_s* player, pspdef_t* psp);
void A_FireBFG(struct player_s* player, pspdef_t* psp);
void A_BFGSpray(mobj_t* mo);
void A_FireOldBFG(struct player_s* player, pspdef_t* psp);

// [XA] New mbf21 codepointers

void A_WeaponProjectile(struct player_s* player, pspdef_t* psp);
void A_WeaponBulletAttack(struct player_s* player, pspdef_t* psp);
void A_WeaponMeleeAttack(struct player_s* player, pspdef_t* psp);
void A_WeaponSound(struct player_s* player, pspdef_t* psp);
void A_WeaponAlert(struct player_s* player, pspdef_t* psp);
void A_WeaponJump(struct player_s* player, pspdef_t* psp);
void A_ConsumeAmmo(struct player_s* player, pspdef_t* psp);
void A_CheckAmmo(struct player_s* player, pspdef_t* psp);
void A_RefireTo(struct player_s* player, pspdef_t* psp);
void A_GunFlashTo(struct player_s* player, pspdef_t* psp);

// heretic

void P_RepositionMace(mobj_t* mo);
void P_ActivateBeak(struct player_s* player);
void P_PostChickenWeapon(struct player_s* player, WeaponType weapon);
void P_SetPsprite(struct player_s* player, PspNum position, StateId stnum);
void P_SetPspritePtr(struct player_s* player, pspdef_t* psp, StateId stnum);
void P_OpenWeapons();
void P_CloseWeapons();
void P_AddMaceSpot(const mapthing_t* mthing);
void P_DropWeapon(struct player_s* player);
void P_UpdateBeak(struct player_s* player, pspdef_t* psp);

// hexen

void P_SetPspriteNF(struct player_s* player, PspNum position, StateId stnum);
void P_PostMorphWeapon(struct player_s* player, WeaponType weapon);
void P_ActivateMorphWeapon(struct player_s* player);

#ifdef __cplusplus
}
#endif
