// SPDX-License-Identifier: GPL-2.0-or-later

// DESCRIPTION:
//	The Compet-N and SDA demo archives, one test per demo.
//
//	The archives are not in the repository (`spec/support/fetch_archive.py`
//	downloads them), but their indexes are, next to them:
//	`spec/support/archive/competn-2005.json` and `spec/support/archive/sda-2005.json`,
//	generated by `spec/support/index_archive.py`.
//	A suite is registered only when its archive is unpacked in
//	`spec/support/archive/`, and each test replays its demo straight out of
//	the zip and expects the time recorded as `measured`.
//
//	There are thousands of these, too many for CTest to discover one by one,
//	so `spec/CMakeLists.txt` runs them in GTest shards instead.

#include <algorithm>
#include <array>
#include <cctype>
#include <cstddef>
#include <cstdint>
#include <format>
#include <fstream>
#include <iostream>
#include <memory>
#include <optional>
#include <set>
#include <stdexcept>
#include <string>
#include <vector>

#include <gtest/gtest.h>
#include <nlohmann/json.hpp>
#include <zip.h>

#include "ArchiveTest.hpp"
#include "DemoRun.hpp"
#include "Levelstat.hpp"
#include "SpecEnvironment.hpp"
#include "Text.hpp"

namespace
{
	struct Archive
	{
		// Directory in `spec/support/archive`, with its index `<name>.json` beside it.
		std::string_view name;
		std::string_view suite;
	};

	constexpr std::array k_archives {
		Archive { .name = "competn-2005", .suite = "Competn2005" },
		Archive { .name = "sda-2005", .suite = "Sda2005" },
	};

	struct ArchiveDemo
	{
		// Unpacked archive directory the zip path is relative to.
		std::filesystem::path archive;
		std::string zip;
		// The zip inside `zip` that holds the demo, if any.
		std::optional<std::string> nestedZip;
		std::string lump;
		std::optional<std::string> iwad;
		std::vector<std::string> pwads;
		// The files `measure_archive.py` chose for `pwads`, relative to `spec/support/wads`.
		std::optional<std::vector<std::string>> pwadFiles;
		// The time upstream reached, as `Levelstat::TotalTime` reads it; "00:00" when it finished no level.
		std::optional<std::string> measured;
	};

	/** An open zip, read-only, together with the bytes it was opened from (if any). */
	class ZipArchive
	{
	public:
		explicit ZipArchive(const std::filesystem::path& file)
		{
			int32_t error = 0;
			m_zip = zip_open(file.string().c_str(), ZIP_RDONLY, &error);

			if(m_zip == nullptr)
				throw std::runtime_error(std::format("cannot open '{}' (libzip error {})", file.string(), error));
		}

		/** A zip stored inside another one. */
		explicit ZipArchive(std::vector<std::byte> contents)
			: m_contents(std::move(contents))
		{
			zip_error_t error;
			zip_error_init(&error);

			zip_source_t* source = zip_source_buffer_create(m_contents.data(), m_contents.size(), 0, &error);

			if(source != nullptr)
			{
				m_zip = zip_open_from_source(source, ZIP_RDONLY, &error);

				if(m_zip == nullptr)
					zip_source_free(source);
			}

			const std::string message = zip_error_strerror(&error);
			zip_error_fini(&error);

			if(m_zip == nullptr)
				throw std::runtime_error(std::format("cannot open a nested zip: {}", message));
		}

		~ZipArchive()
		{
			zip_discard(m_zip);
		}

		DOOM_NO_COPY(ZipArchive)
		DOOM_NO_MOVE(ZipArchive)

		/** Whether libzip can unpack `member`; it has no "shrink" or "implode", which old zips use. */
		[[nodiscard]] bool CanRead(const std::string& member) const
		{
			zip_stat_t stat;

			if(zip_stat(m_zip, member.c_str(), 0, &stat) != 0 || (stat.valid & ZIP_STAT_COMP_METHOD) == 0)
				return true;

			return zip_compression_method_supported(stat.comp_method, 0) != 0;
		}

		[[nodiscard]] std::vector<std::byte> Read(const std::string& member) const
		{
			const zip_int64_t index = zip_name_locate(m_zip, member.c_str(), 0);

			if(index < 0)
				throw std::runtime_error(std::format("'{}' is not in the zip", member));

			zip_stat_t stat;

			if(zip_stat_index(m_zip, static_cast<zip_uint64_t>(index), 0, &stat) != 0)
				throw std::runtime_error(std::format("cannot read the size of '{}'", member));

			const std::unique_ptr<zip_file_t, decltype(&zip_fclose)> file(
				zip_fopen_index(m_zip, static_cast<zip_uint64_t>(index), 0), &zip_fclose
			);

			if(file == nullptr)
				throw std::runtime_error(std::format("cannot open '{}' in the zip", member));

			std::vector<std::byte> contents(static_cast<std::size_t>(stat.size));

			if(zip_fread(file.get(), contents.data(), contents.size()) != static_cast<zip_int64_t>(contents.size()))
				throw std::runtime_error(std::format("cannot read '{}' from the zip", member));

			return contents;
		}

	private:
		// Must outlive `m_zip`, which reads from it.
		std::vector<std::byte> m_contents;
		zip_t* m_zip = nullptr;
	};

	/** The demo's bytes, or nothing when libzip cannot unpack how they are stored. */
	[[nodiscard]] std::optional<std::vector<std::byte>> ReadDemo(const ArchiveDemo& demo)
	{
		const ZipArchive outer(demo.archive / demo.zip);

		if(!demo.nestedZip)
		{
			if(!outer.CanRead(demo.lump))
				return std::nullopt;

			return outer.Read(demo.lump);
		}

		if(!outer.CanRead(*demo.nestedZip))
			return std::nullopt;

		const ZipArchive inner(outer.Read(*demo.nestedZip));

		if(!inner.CanRead(demo.lump))
			return std::nullopt;

		return inner.Read(demo.lump);
	}

	/** DeHackEd patches load with `-deh`, everything else with `-file`. */
	[[nodiscard]] bool IsPatch(const std::filesystem::path& file)
	{
		std::string extension = file.extension().string();

		// `std::tolower` is only defined for values an `uint8_t` can hold.
		std::ranges::transform(extension, extension.begin(), [](const char c) { return static_cast<char>(std::tolower(static_cast<uint8_t>(c))); });

		return extension == ".deh" || extension == ".bex";
	}

	/** Turn a path into something usable as a test name. */
	[[nodiscard]] std::string SanitiseName(const std::string_view path)
	{
		std::string name;

		for(const char c : path)
		{
			const bool isWord = (c >= '0' && c <= '9') || (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z');
			name += isWord ? c : '_';
		}

		return name;
	}

	class ArchiveDemoTest final : public ::testing::Test
	{
	public:
		explicit ArchiveDemoTest(ArchiveDemo demo)
			: m_demo(std::move(demo))
		{
		}

		void TestBody() override
		{
			if(!m_demo.measured)
				GTEST_SKIP() << "not measured yet";

			if(!m_demo.iwad)
				GTEST_SKIP() << "the index does not know its IWAD";

			// A name alone is ambiguous (unrelated WADs share names, and WADs had
			// several versions), so only the exact files upstream was measured with.
			if(!m_demo.pwads.empty() && !m_demo.pwadFiles)
				GTEST_SKIP() << "no file chosen for " << Spec::Join(m_demo.pwads, ", ");

			// The PWADs go into `extra`, all WADs after one `-file` and all patches
			// after one `-deh`: given twice, an option only keeps its last use.
			std::string wads;
			std::string patches;

			for(const std::string& pwad : m_demo.pwadFiles.value_or(std::vector<std::string> {}))
			{
				const std::filesystem::path file = Spec::WadPath(pwad);

				if(!std::filesystem::exists(file))
					GTEST_SKIP() << "missing input: " << pwad << " (spec/support/measure_archive.py extracts it from the idgames mirror)";

				(IsPatch(file) ? patches : wads) += std::format(" \"{}\"", file.string());
			}

			std::string extra;

			if(!wads.empty())
				extra += " -file" + wads;

			if(!patches.empty())
				extra += " -deh" + patches;

			const TemporaryDirectory directory;
			const std::filesystem::path lmp = directory.Path() / std::filesystem::path(m_demo.lump).filename();

			{
				const std::optional<std::vector<std::byte>> contents = ReadDemo(m_demo);

				if(!contents)
					GTEST_SKIP() << "libzip cannot unpack the demo's compression (shrink or implode)";

				std::ofstream file(lmp, std::ios::binary);
				file.write(reinterpret_cast<const char*>(contents->data()), static_cast<std::streamsize>(contents->size()));
			}

			const std::string lmpPath = lmp.string();
			const DemoOptions options {
				.lmp = lmpPath,
				.iwad = *m_demo.iwad,
				.pwad = {},
				.extra = extra,
			};
			SPEC_REQUIRE_INPUTS(options);

			// Through `Levelstat` rather than `DemoRun::TotalTime`: "00:00" is a
			// measurement too - upstream finished no level - and must match as well.
			const DemoRun run(options);
			const auto total = Levelstat::Parse(run.LevelstatText()).TotalTime();

			ASSERT_TRUE(total) << total.error();
			EXPECT_EQ(*total, *m_demo.measured);
		}

	private:
		ArchiveDemo m_demo;
	};

	[[nodiscard]] std::optional<std::string> OptionalString(const nlohmann::json& entry, const char* key)
	{
		const auto found = entry.find(key);

		if(found == entry.end() || found->is_null())
			return std::nullopt;

		return found->get<std::string>();
	}

	void RegisterArchive(const Archive& archive)
	{
		const std::filesystem::path directory = Spec::DataDirectory() / "support" / "archive" / archive.name;

		// The archive is optional; without it there is nothing to replay.
		if(!std::filesystem::is_directory(directory))
			return;

		const std::filesystem::path index = Spec::DataDirectory() / "support" / "archive" / std::format("{}.json", archive.name);
		std::ifstream file(index);

		if(!file)
		{
			// Notices go to stderr so they never reach `--gtest_list_tests` output.
			std::cerr << std::format("[ spec     ] no index at '{}' for the unpacked {}\n", index.string(), archive.name);
			return;
		}

		const std::string suite(archive.suite);
		std::set<std::string> names;

		for(const nlohmann::json& entry : nlohmann::json::parse(file))
		{
			ArchiveDemo demo {
				.archive = directory,
				.zip = entry.at("zip").get<std::string>(),
				.nestedZip = OptionalString(entry, "nested_zip"),
				.lump = entry.at("lump").get<std::string>(),
				.iwad = OptionalString(entry, "iwad"),
				.pwads = entry.at("pwads").get<std::vector<std::string>>(),
				.pwadFiles = entry.contains("pwad_files")
					? std::optional(entry.at("pwad_files").get<std::vector<std::string>>())
					: std::nullopt,
				.measured = OptionalString(entry, "measured"),
			};

			// Paths differing only in punctuation would collide, so number repeats.
			const std::string base = SanitiseName(std::format("{}/{}/{}", demo.zip, demo.nestedZip.value_or(""), demo.lump));
			std::string name = base;

			for(int32_t repeat = 2; names.contains(name); ++repeat)
				name = std::format("{}_{}", base, repeat);

			names.insert(name);

			::testing::RegisterTest(
				suite.c_str(), name.c_str(), nullptr, nullptr, __FILE__, __LINE__,
				[demo = std::move(demo)]() -> ::testing::Test*
				{
					return new ArchiveDemoTest(demo);
				}
			);
		}
	}
}

void RegisterArchiveDemos()
{
	for(const Archive& archive : k_archives)
		RegisterArchive(archive);
}
